# django-core-utils-test travis config file

language: python
sudo: true

python: '3.6'

services:
  - docker
env:
  global:
    - COMPOSE_VERSION=1.6.2
    - SERVICE='web-test'
  matrix:
    - TOXENV=py36-django11115
    - TOXENV=py36-django211
    - COMPOSE_FILE='docker-compose-sqlite.yml' 
    - COMPOSE_FILE='docker-compose-mysql.yml'
    - COMPOSE_FILE='docker-compose-postgres.yml'
 
matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: TOXENV=py27-django11115
    - python: '3.5'
      env: TOXENV=py35-django11115
    - python: '3.5'
      env: TOXENV=py35-django211
    - python: '3.7'
      env: TOXENV=py37-django211
      dist: xenial
      sudo: true

before_install:
- docker -v
- if [[ $COMPOSE_FILE ]]; 
  then ./docker_update.sh;
  fi


script:
  - if [ -z "$COMPOSE_FILE" ]; 
    then tox -e $TOXENV;
    else docker-compose -f $COMPOSE_FILE up --abort-on-container-exit ;
    fi

install:
  - pip install tox


notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop