# docker-compose mysql configuration file
version: "3"
services:
  db-mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
    # In a 'real' environment passwords will be defined in the environment
    # by only using the key
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=test_user
    - MYSQL_PASSWORD=test_user
    - MYSQL_DATABASE=django_core_utils
    
  web-test:
    build: 
      context: .
      dockerfile: docker-dockerfile-mysql.yml
    command: ./docker_run_tests.sh -w 15 -t mysql -d db-mysql
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-mysql
    env_file: 
      - docker_env/common
      - docker_env/mysql
      
  
