# docker-compose sqlite configuration file
version: '2'
services:
  web-sqlite:
    build:
      context: .
      dockerfile: docker-dockerfile-sqlite.yml
    command: ./docker_run_tests.sh -d 1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: 
      - docker_env/common
      - docker_env/sqlite

